# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_duration', models.IntegerField(blank=True, null=True)),
                ('base_cost', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('descr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cost',
            },
        ),
        migrations.CreateModel(
            name='UserCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_duration', models.IntegerField(blank=True, null=True)),
                ('base_cost', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('descr', models.CharField(max_length=100)),
                ('creatime', models.DateTimeField(blank=True, null=True)),
                ('startime', models.DateTimeField(blank=True, null=True)),
                ('cost_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usercost',
            },
        ),
    ]
