# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recommender_id', models.CharField(max_length=32, null=True)),
                ('login_name', models.CharField(max_length=128)),
                ('login_passwd', models.CharField(max_length=128)),
                ('status', models.NullBooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.DateTimeField(null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('real_name', models.CharField(max_length=128)),
                ('idcard_no', models.CharField(max_length=128)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.NullBooleanField()),
                ('occupation', models.CharField(max_length=128, null=True)),
                ('telephone', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('mailaddress', models.CharField(max_length=256, null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('qq', models.IntegerField(null=True)),
                ('last_login_time', models.DateTimeField(auto_now=True, null=True)),
                ('last_login_ip', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
